# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'UIFaster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIFaster
#  pod 'GrowingTextView', '0.7.2'
  pod 'RxSwift', '6.6.0'
  pod 'RxCocoa', '6.6.0'
end
